# prettier-ignore
# DEFINE A GITHUB WORKFLOW PIPELINE
# name of the workflow
name: NASA Project CI

# define the events that trigger the workflow
on:
   push:
      branches: [main]
   pull_request:
      branches: [main]

# jobs to accomplish on the triggering events
jobs:
   # name of the jobs
   build:
      env:
         # Tells GitHub we are in CI environment and disables watch mode which is necessary for running 'npm test' task
         CI: true
         # PORT: 9000
      strategy:
         matrix:
            node-version: [14.x, 16.x, 20.x]
      runs-on: ubuntu-latest
      steps:
         # Action #1 - Built-in GitHub checkout action
         # About script: This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
         - uses: actions/checkout@v4 # Action script without a tag
         # Action #2 -
         # Provide tag for the action
         - name: Use Node.js version ${{matrix.node-version}}
           uses: actions/setup-node@v4
           # Pass in option for node-version
           with:
              # node-version: "20"
              node-version: ${{matrix.node-version}}
         # Install npm
         - run: npm install
         # Run npm commands from package.json @ project root
         - run: npm run build_mac --prefix client
         - run: npm test

   # deploy:
   #    needs: build
